<a href="https://colab.research.google.com/github/ftltnbs/DAwPy/blob/master/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats 

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [4]:
samples = np.random.normal(100, 15, 1000) #mean 100, sd 15
print(samples)

[ 99.05908585 108.32159012  94.19494501  79.39460849  63.86269827
 111.16062666  94.27936668 102.06369139  96.76295401  90.09264207
 103.75222306 105.36183077 116.01281224 110.13565171  79.84287315
  92.93658845 122.88792626  99.46444518  95.96439608 113.30440117
 103.08820386  86.95797609 116.97277019  85.56626241  77.84065419
  73.7974996   74.94098871  68.70371036 100.01343071  92.29638725
 106.96356921  97.1116396   92.26918557 118.81126078 101.88772509
  87.47793988  97.33701642 106.99493893  95.25082562 101.01310618
  90.09489721  68.38613516 103.74006425 100.12274106 108.72400608
  91.25174983 107.52225466 121.64500696 115.98816426 118.63388711
  87.89826119 118.51680515  99.97366346  99.96965903  74.70369934
  95.44314812  94.50081005  81.3220978  108.8235847   88.56729193
 105.35809474 124.36049554 111.13956946 107.50583682 126.69743378
 102.30088874  91.57597268 122.38022393  82.11973856  97.36258301
 118.80874775  93.66673792  87.56210205 100.13997774  93.44316443
 114.14072

Compute the **mean**, **median**, and **mode**

In [7]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print(mean)
print(median)
print(mode)

100.64415751139025
100.41630537821749
ModeResult(mode=array([56.03514849]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [8]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = q3-q1
print(min,max,q1,q3,iqr,sep='\n')

56.03514848889664
151.99004588407493
91.15803861381688
110.7392706966091
19.581232082792212


Compute the **variance** and **standard deviation**

In [9]:
variance = np.var(samples)
std_dev = np.std(samples)
print(variance,std_dev, sep='\n' )

212.0244726258904
14.561060147732734


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [10]:
skw = stats.skew(samples)
kur = stats.kurtosis(samples)
print(skw,kur, sep='/n')

0.036703374036168475/n-0.0729458913990566


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [12]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [13]:
np.random.rand(1,10)


array([[0.17643286, 0.57015265, 0.03203911, 0.98870748, 0.32332653,
        0.47688522, 0.99496693, 0.00373529, 0.27133682, 0.92755873]])

In [14]:
np.random.randn(10)

array([ 0.10944287, -0.58141652,  1.49262847, -1.10037467,  0.33284594,
       -0.28456022,  0.678893  ,  1.71639602,  0.09494652, -1.65932464])

In [16]:
np.random.random(10)

array([0.4500704 , 0.00828933, 0.02804343, 0.2728967 , 0.29693827,
       0.38775051, 0.33723152, 0.18790573, 0.67949714, 0.61431906])

In [21]:
y = np.array(np.random.randn(10), dtype =int)
y

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [23]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.26590801],
       [0.26590801, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [24]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [25]:
from scipy.stats.mstats_basic import pearsonr
r = pearsonr(x,y)
r

(0.7586402890911869, masked_array(data=0.01096434,
              mask=False,
        fill_value=1e+20))

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [26]:
rho =stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [27]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

Call the relevant method to calculate pairwise Pearson's r correlation of columns